plugins:
  - rubocop-minitest
  - rubocop-rake

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "coverage/**/*"
    - "vendor/**/*"
    - "tmp/**/*"

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/BlockLength:
  Enabled: false

Metrics/ClassLength:
  Max: 240

Metrics/MethodLength:
  Max: 40

Metrics/AbcSize:
  Max: 35

Metrics/ParameterLists:
  CountKeywordArgs: false

Minitest/MultipleAssertions:
  Max: 12
